spring:

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8083

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 15m
    refresh-token-expiration: 30d