services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: finflow-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:17
    container_name: finflow-auth-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - auth-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:17
    container_name: finflow-payment-db

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - payment-db-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payment_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fraud-db:
    image: postgres:17
    container_name: finflow-fraud-db

    ports:
      - "5434:5432"

    environment:
      POSTGRES_DB: fraud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - fraud-db-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fraud_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth-db-data:
  payment-db-data:
  fraud-db-data:
