apiVersion: v1
kind: Pod

metadata:
  name: payment-service-pod

spec:
  containers:
    - name: payment-service
      image: docker-payment-service:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8081