spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5434/fraud_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true

logging:
  level:
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG